### ISSUE TITLE
Can't restitute knox/gateway_topologies

### ISSUE THREAD

**Issue by mehdibn** [TOSIT-IO/tdp-ui#149]
`type error` when Knox - gateway_topology / tdpldap var is loaded.

**Comment by mehdibn** [comment]
var value :
```
gateway_topology:
  tdpldap:
    providers:
      authentication:
        name: ShiroProvider
        parameters:
          main.ldapRealm: org.apache.hadoop.gateway.shirorealm.KnoxLdapRealm
          main.ldapRealm.contextFactory.authenticationMechanism: simple
          main.ldapRealm.contextFactory.url: ldap://{{ groups['ldap'] | first | tosit.tdp.access_fqdn(hostvars) }}:389
          main.ldapRealm.userDnTemplate: uid={0},ou=users,c=io
          sessionTimeout: 30
          urls./**: authcBasic
          main.ldapRealm.contextFactory.systemUsername: cn=Manager,ou=tdp,o=tosit,c=io
          main.ldapRealm.contextFactory.systemPassword: secret
      authorization:
        name: AclsAuthz
        parameters:
          webhdfs.acl: '*;*;*'
      ha:
        name: HaProvider
        parameters:
          HIVE: '{{ topology_common_ha_configuration }};zookeeperEnsemble={{ zookeeper_quorum | trim }};zookeeperNamespace=hiveserver2'
          RESOURCEMANAGER: '{{ topology_common_ha_configuration }}'
          WEBHBASE: '{{ topology_common_ha_configuration }}'
          WEBHDFS: '{{ topology_common_ha_configuration }}'
          YARNUI: '{{ topology_common_ha_configuration }}'
          HBASEUI: '{{ topology_common_ha_configuration }}'
          HDFSUI: '{{ topology_common_ha_configuration }}'
          NAMENODE: '{{ topology_common_ha_configuration }}'
      identity-assertion:
        name: Default
    services:
      NAMENODE:
        hosts: '{{ groups[''hdfs_nn''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ hdfs_nn_rpc_port }}'
        scheme: hdfs://
      HDFSUI:
        hosts: '{{ groups[''hdfs_nn''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ hdfs_nn_https_port }}'
        version: 2.7.0
      JOBHISTORYUI:
        hosts:
        - '{{ groups[''mapred_jhs''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | first }}'
        port: '{{ mapred_jhs_https_port }}'
      HIVE: {}
      RANGERUI:
        hosts: '{{ groups[''ranger_admin''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ ranger_adm_https_port }}'
      RESOURCEMANAGER:
        hosts: '{{ groups[''yarn_rm''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        location: /ws
        port: '{{ yarn_rm_https_port }}'
      SPARKHISTORYUI:
        hosts: '{{ groups[''spark_hs''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ spark_hs_https_port }}'
      SPARK3HISTORYUI:
        hosts: '{{ groups[''spark3_hs''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ spark3_hs_https_port}}'
      WEBHBASE:
        hosts: '{{ groups[''hbase_rest''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ hbase_rest_https_port }}'
      WEBHDFS:
        hosts: '{{ groups[''hdfs_nn''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        location: /webhdfs
        port: '{{ hdfs_nn_https_port }}'
      YARNUI:
        hosts: '{{ groups[''yarn_rm''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ yarn_rm_https_port }}'
      HBASEUI:
        hosts: '{{ groups[''hbase_master''] | default([]) | map(''tosit.tdp.access_fqdn'', hostvars) | list }}'
        port: '{{ hbase_master_info_https_port }}'
```
